export const AssetObjectDataTypes = [
  {
    id: 1,
    name: "All Objects",
    value: "",
    objectType: ["ROCKET BODY", "DEBRIS", "UNKNOWN", "PAYLOAD"],
    className: "bg-secondary",
  },
  {
    id: 2,
    name: "Payloads",
    value: "",
    objectType: ["PAYLOAD"],
    className: "bg-gray-100",
  },
  {
    id: 3,
    name: "Debris",
    value: "",
    objectType: ["DEBRIS"],
    className: "bg-green-500",
  },
  {
    id: 4,
    name: "Rocket Bodies",
    value: "",
    objectType: ["ROCKET BODY"],
    className: "bg-yellow-400",
  },
  {
    id: 5,
    name: "Unknown",
    value: "",
    objectType: ["UNKNOWN"],
    className: "bg-red-500",
  },
];
export const AssetObjectTypes = ["ROCKET BODY", "DEBRIS", "UNKNOWN", "PAYLOAD"];
export const AssetAttributes = [
  "noradCatId",
  "intlDes",
  "name",
  "launchDate",
  "decayDate",
  "objectType",
  "launchSiteCode",
  "countryCode",
  "orbitCode",
];
export const AssetOrbitCode = [
  "LEO",
  "LEO1",
  "LEO2",
  "LEO3",
  "LEO4",
  "MEO",
  "GEO",
  "HEO",
  "IGO",
  "EGO",
  "NSO",
  "GTO",
  "GHO",
  "HAO",
  "MGO",
  "LMO",
  "UFO",
  "ESO",
  "UNKNOWN",
];
